### ISSUE TITLE
`showyourk build` fails with `KeyError`

### ISSUE THREAD

**Issue by wtbarnes** [jwreep/ebtel_abundances#2]
When running `showyourwork build`, I get the following exception,

```python traceback
Traceback (most recent call last):
  File "/Users/wtbarnes/Documents/papers/ebtel_abundances/.snakemake/scripts/tmpudpk6fz0.preprocess.py", line 495, in <module>
    config["tree"] = get_json_tree(snakemake.input[0])
  File "/Users/wtbarnes/Documents/papers/ebtel_abundances/.snakemake/scripts/tmpudpk6fz0.preprocess.py", line 411, in get_json_tree
    free_floating_graphics = [
  File "/Users/wtbarnes/Documents/papers/ebtel_abundances/.snakemake/scripts/tmpudpk6fz0.preprocess.py", line 414, in <listcomp>
    if graphic not in config["tex_files_out"]
KeyError: 'tex_files_out'
Error in rule syw__preprocess:
    jobid: 1
    output: .showyourwork/config.json

RuleException:
CalledProcessErrorin line 98 of /Users/wtbarnes/mambaforge/lib/python3.9/site-packages/showyourwork/workflow/rules/preprocess.smk:
Command 'set -euo pipefail;  /Users/wtbarnes/mambaforge/bin/python3.9 /Users/wtbarnes/Documents/papers/ebtel_abundances/.snakemake/scripts/tmpudpk6fz0.preprocess.py' returned non-zero exit status 1.
  File "/Users/wtbarnes/mambaforge/lib/python3.9/site-packages/showyourwork/workflow/rules/preprocess.smk", line 98, in __rule_4
  File "/Users/wtbarnes/mambaforge/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Exiting because a job execution failed. Look above for error message
```

This is also happening on the CI.

**Comment by jwreep** [comment]
Yeah, this one is [the OrcID issue that I posted about](https://github.com/showyourwork/showyourwork/issues/454) on showyourwork's repository.  The solution is [in this comment.](https://github.com/showyourwork/showyourwork/issues/400#issuecomment-1729999403)  Alternatively, delete the OrcIDs from the author list.  

I don't know the inner workings of showyourwork well enough to know why that would cause an issue...

**Comment by jwreep** [comment]
Solved upstream.
